## install.packages("data.table")
library(data.table)
png(filename='plot1.png')
cons <- fread("household_power_consumption.txt")
cons <- cons[cons$Date == '2/2/2007' | cons$Date == '1/2/2007',]
cons$Time <- as.POSIXct(strptime(paste(cons$Date, cons$Time, sep=' '), "%d/%m/%Y %H:%M:%S"))
cons$Date <- as.Date(cons$Date, format='%d/%m/%Y')
cons$Global_active_power <- as.numeric(cons$Global_active_power)
cons$Global_reactive_power <- as.numeric(cons$Global_reactive_power)
cons$Voltage <- as.numeric(cons$Voltage)
cons$Global_intensity <- as.numeric(cons$Global_intensity)
cons$Sub_metering_1 <- as.numeric(cons$Sub_metering_1)
cons$Sub_metering_2 <- as.numeric(cons$Sub_metering_1)
cons$Sub_metering_3 <- as.numeric(cons$Sub_metering_1)
hist(cons$Global_active_power, col='red', main='Global Active Power', xlab='Global Active Power (kilowatts)')
dev.off()